create table country
(
    id        bigint generated by default as identity primary key,
    name      varchar(255),
    continent varchar(255)
);

create table host
(
    id         bigint generated by default as identity primary key,
    name       varchar(255),
    surname    varchar(255),
    country_id bigint references country
);


create table accommodation
(
    id       bigint generated by default as identity primary key,
    name     varchar(255),
    category varchar(60),
    host_id  bigint references host,
    numRooms integer
);


create table airbnb_users
(
    username                   varchar(255) primary key,
    password                   varchar(255),
    name                       varchar(255),
    surname                    varchar(255),
    is_account_non_expired     boolean default true,
    is_account_non_locked      boolean default true,
    is_credentials_non_expired boolean default true,
    is_enabled                 boolean default true,
    role                       varchar(50)
);

create table reservations_list
(
    id            bigint generated by default as identity
        primary key,
    date_created  timestamp,
    user_username varchar(255) references airbnb_users
);

create table reservations_list_accommodations
(
    reservations_list_id bigint references reservations_list on delete cascade,
    accommodation_id      bigint references accommodation on delete cascade,
    primary key (reservations_list_id, accommodation_id)
);


create index idx_user_username_password on airbnb_users (username, password);
create index idx_user_username on airbnb_users (username);
create index idx_user_role on airbnb_users (role);
